mysite/login/urls.py
from django.conf.urls import patterns, url

from login import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^trylogin/$', views.trylogin, name='trylogin'),    
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', include('login.urls', namespace="login")),
)

mysite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
)

mysite/login/models.py
from django.db import models

class Users(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=250)

class Votes(models.Model):
    username_id = models.IntegerField()
    question_id = models.IntegerField()

mysite/polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date < now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __unicode__(self):
		return self.choice_text
	
class Track(models.Model):
	question = models.ForeignKey(Question)
	choice_id = models.ForeignKey(Choice)
	user = models.CharField(max_length=200)

mysite/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

def index(request):
    return render(request, 'login/login.html')

def trylogin(request):    
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/polls')
    else:
        return redirect('/login')

mysite/polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import logout
from polls.models import Choice, Question, Track
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

def index(request):
    username = ""
    isLoggedIn = request.user.is_authenticated()
    if(isLoggedIn):
        username = request.user.get_username()
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list, 'isLoggedIn': isLoggedIn, 'username': username}
    return render(request, 'polls/index.html', context)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())	

def logout_view(request):
    logout(request)
    return redirect('/polls/')

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        if(request.user.is_authenticated()):
            username = request.user.get_username()
            try:
                hasVoted = Track.objects.get(question = p, user=username)
            except Track.DoesNotExist:
                voteUser= Track(question = p, choice_id = selected_choice, user=username )
                voteUser.save()
                selected_choice.votes += 1
                selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/login/templates/login/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset = "UTF-8">
        <title>Login Page</title>

</head>

<body>
        <h1> Login </h1>
        <div id = "content">
                <form name="login" action="{% url 'login:trylogin' %}" method="post">
                        {% csrf_token %}
			<span class="block">
                        Username: <input type="text" id="username" name="username" required />
                        Password: <input type="password" id="password" name = "password" required/>
                        <input type="submit" value="Login">
                        </span>
                </form>
        </div>
</body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset = "UTF-8">
        <title>Index Page</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset = "UTF-8">
        <title>Index Page</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

</head>
<body>
{% if isLoggedIn %}
<h1>Welcome {{username }}</h1>
<form name="logout" action="{% url 'polls:logout_view' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Logout">
</form>
{% else %}
{% endif %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
	<meta charset = "UTF-8">
        <title>Results  Page</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>